"""empty message

Revision ID: 1d7d6fe675a9
Revises: b70f9184648
Create Date: 2015-12-12 20:34:00.665109

"""

# revision identifiers, used by Alembic.
revision = '1d7d6fe675a9'
down_revision = 'b70f9184648'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta')
    ### end Alembic commands ###
